"""Look up pre-computed annual ground loads for DOE prototype buildings.

Reads data/public/prototype_loads.json, keyed by building_type → climate_zone.
Values represent ASHRAE three-pulse ground loads (Philippe et al. 2010 convention).
Sign convention: negative = heating-dominant, positive = cooling-dominant.

Pre-computed from EnergyPlus with ZoneHVAC:IdealLoadsAirSystem at the DOE
prototype reference floor area.  If the user requests a different floor area,
the normalized W/m² values are scaled to match.

Generated by: scripts/precompute_loads.py
Reference:    Deru et al. (2011) NREL/TP-5500-46861.
"""

import json
import pathlib
from geosite.models import LoadPulses

_DEFAULT_JSON = pathlib.Path(__file__).parents[2] / "data/public/prototype_loads.json"


def lookup_prototype_loads(
    building_type: str,
    climate_zone: str,
    target_area_m2: float | None = None,
    loads_json: pathlib.Path = _DEFAULT_JSON,
) -> LoadPulses:
    """Return three-pulse ground loads for a building type, climate zone, and area.

    Parameters
    ----------
    building_type   : key matching prototype_loads.json (e.g. "small_office")
    climate_zone    : ASHRAE climate zone (e.g. "5A", "3B", "2A")
    target_area_m2  : user's floor area in m².  If None, returns values at the
                      DOE prototype reference area.  If provided, scales the
                      pre-computed loads by (target_area_m2 / prototype_area_m2)
                      using the stored W/m² normalized values.

    Returns
    -------
    LoadPulses following the Philippe et al. (2010) sign convention.

    Raises
    ------
    KeyError  : if the building_type or climate_zone is not in the table.
    """
    with open(loads_json) as f:
        table = json.load(f)

    if building_type not in table:
        raise KeyError(
            f"'{building_type}' not in prototype loads table. "
            f"Available: {sorted(k for k in table if not k.startswith('_'))}"
        )

    building_table = table[building_type]
    if climate_zone not in building_table:
        raise KeyError(
            f"Climate zone '{climate_zone}' not found for '{building_type}'. "
            f"Available zones: {sorted(k for k in building_table if not k.startswith('_'))}"
        )

    entry = building_table[climate_zone]

    def _both_mode_peaks(q_h: float, q_m: float) -> dict:
        """Derive both-mode peaks when peak_heat_kW / peak_cool_kW are stored.

        The monthly average for the cross-mode is estimated using the dominant
        mode's |q_m|/|q_h| ratio — a reasonable first-order approximation for
        a feasibility tool (the load shape is similar across modes).
        """
        if "peak_heat_kW" not in entry or "peak_cool_kW" not in entry:
            return {}
        ratio = abs(q_m / q_h) if q_h != 0 else 0.33
        q_h_heat = -abs(float(entry["peak_heat_kW"]) * 1000.0)
        q_h_cool = abs(float(entry["peak_cool_kW"]) * 1000.0)
        return dict(
            q_h_heat=q_h_heat,
            q_m_heat=q_h_heat * ratio,
            q_h_cool=q_h_cool,
            q_m_cool=q_h_cool * ratio,
        )

    def _corrected_q_y(raw_q_y: float) -> float:
        """Correct q_y for the ZoneHVAC:IdealLoadsAirSystem artifact.

        EnergyPlus with IdealLoads counts simultaneous per-zone heating and
        cooling without heat recovery, inflating annual cooling energy by ~3x
        in cold climates.  For heating-dominant climate zones (5A and colder),
        we cap annual cooling at 2× annual heating, then recompute q_y.

        Professor-validated target for Chicago (5A): heat:cool ≈ 1:2.
        """
        cold_zones = {"5A", "5B", "6A", "6B", "7", "8"}
        if climate_zone not in cold_zones:
            return raw_q_y
        if "ann_heat_kWh" not in entry or "ann_cool_kWh" not in entry:
            return raw_q_y
        ann_heat = float(entry["ann_heat_kWh"])
        ann_cool = float(entry["ann_cool_kWh"])
        # Cap cooling at 2× heating to match empirical heat:cool ≈ 1:2
        ann_cool_corrected = min(ann_cool, ann_heat * 2.0)
        return (ann_cool_corrected - ann_heat) * 1000.0 / 8760.0

    # Area-scaled path: use normalised W/m² values.
    if target_area_m2 is not None and "q_h_Wpm2" in entry:
        proto_area = float(building_table.get("_area_m2", 1.0))
        area = float(target_area_m2)
        q_h = float(entry["q_h_Wpm2"]) * area
        q_m = float(entry["q_m_Wpm2"]) * area
        bm = _both_mode_peaks(q_h, q_m)
        # Scale cross-mode peaks by (area / proto_area) because peak_*_kW are at proto area
        if bm:
            scale = area / proto_area
            bm = {k: v * scale for k, v in bm.items()}
        raw_q_y = float(entry["q_y_Wpm2"]) * area
        return LoadPulses(
            q_h=q_h,
            q_m=q_m,
            q_y=_corrected_q_y(raw_q_y),
            **bm,
        )

    # Legacy path: absolute prototype values.
    q_h = float(entry["q_h"])
    q_m = float(entry["q_m"])
    return LoadPulses(
        q_h=q_h,
        q_m=q_m,
        q_y=_corrected_q_y(float(entry["q_y"])),
        **_both_mode_peaks(q_h, q_m),
    )
