"""Look up pre-computed annual ground loads for DOE prototype buildings.

Reads data/public/prototype_loads.json, keyed by building_type → climate_zone.
Values represent ASHRAE three-pulse ground loads (Philippe et al. 2010 convention).
Sign convention: negative = heating-dominant, positive = cooling-dominant.

Pre-computed from EnergyPlus with ZoneHVAC:IdealLoadsAirSystem at the DOE
prototype reference floor area.  If the user requests a different floor area,
the normalized W/m² values are scaled to match.

Generated by: scripts/precompute_loads.py
Reference:    Deru et al. (2011) NREL/TP-5500-46861.
"""

import json
import pathlib
from geosite.models import LoadPulses

_DEFAULT_JSON = pathlib.Path(__file__).parents[2] / "data/public/prototype_loads.json"


def lookup_prototype_loads(
    building_type: str,
    climate_zone: str,
    target_area_m2: float | None = None,
    loads_json: pathlib.Path = _DEFAULT_JSON,
) -> LoadPulses:
    """Return three-pulse ground loads for a building type, climate zone, and area.

    Parameters
    ----------
    building_type   : key matching prototype_loads.json (e.g. "small_office")
    climate_zone    : ASHRAE climate zone (e.g. "5A", "3B", "2A")
    target_area_m2  : user's floor area in m².  If None, returns values at the
                      DOE prototype reference area.  If provided, scales the
                      pre-computed loads by (target_area_m2 / prototype_area_m2)
                      using the stored W/m² normalized values.

    Returns
    -------
    LoadPulses following the Philippe et al. (2010) sign convention.

    Raises
    ------
    KeyError  : if the building_type or climate_zone is not in the table.
    """
    with open(loads_json) as f:
        table = json.load(f)

    if building_type not in table:
        raise KeyError(
            f"'{building_type}' not in prototype loads table. "
            f"Available: {sorted(k for k in table if not k.startswith('_'))}"
        )

    building_table = table[building_type]
    if climate_zone not in building_table:
        raise KeyError(
            f"Climate zone '{climate_zone}' not found for '{building_type}'. "
            f"Available zones: {sorted(k for k in building_table if not k.startswith('_'))}"
        )

    entry = building_table[climate_zone]

    # If the entry contains normalized W/m² values and a target area was given,
    # scale to the user's floor area.
    if target_area_m2 is not None and "q_h_Wpm2" in entry:
        proto_area = float(building_table.get("_area_m2", 1.0))
        area = float(target_area_m2)
        return LoadPulses(
            q_h=float(entry["q_h_Wpm2"]) * area,
            q_m=float(entry["q_m_Wpm2"]) * area,
            q_y=float(entry["q_y_Wpm2"]) * area,
        )

    # Legacy path: return absolute prototype values (fixture or pre-computed at ref area)
    return LoadPulses(
        q_h=float(entry["q_h"]),
        q_m=float(entry["q_m"]),
        q_y=float(entry["q_y"]),
    )
